version: '3.8'

services:
  postgres11:
    image: postgres:13
    container_name: postgres11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cem123
      POSTGRES_DB: eva-exchange
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-eva-exchange
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - postgres11
    volumes:
      - ./src:/app/src

volumes:
  redis_data:
  pgdata:
